common: 
  dataset_path: ../datasets/data/p2p/
  
  # class_a_choice: "chair/chair_skeleton"
  # class_b_choice: "chair/chair_surface"
  # weight_path: weights/p2p/chair_skeleton_surface

  # class_a_choice: "airplane/airplane_skeleton"
  # class_b_choice: "airplane/airplane_surface"
  # weight_path: weights/p2p/airplane_skeleton_surface
  
  # class_a_choice: "chair/chair_scan"
  # class_b_choice: "chair/chair_surface"
  # weight_path: weights/p2p/chair_scan_surface
  
  # class_a_choice: "airplane/airplane_scan"
  # class_b_choice: "airplane/airplane_surface"
  # weight_path: weights/p2p/airplane_scan_surface
  
  # class_a_choice: "bed/bed_profile"
  # class_b_choice: "bed/bed_surface"
  # weight_path: weights/p2p/bed_profile_surface
  
  class_a_choice: "sofa/sofa_profile"
  class_b_choice: "sofa/sofa_surface"
  weight_path: weights/p2p/sofa_profile_surface


  point_num: 2048

  support: 10
  DEGREE: [2, 2, 2, 2, 2, 4, 16]
  G_FEAT: [256, 512, 256, 256, 128, 128, 64, 3]
  D_FEAT: [3,  64,  128, 256, 512]
  z_size: 256

  num_classes: 2

  input_channels: 0     # feature channels except (x, y, z)
  relation_prior: 1


train:
  batch_size: 8
  e_lr: 0.0001 # 0-100: 0.0004 100-200: 0.0002 200-: 0.0001
  t_lr: 0.0005 # 0-100: 0.0020 100-200: 0.0010 200-: 0.0005
  d_lr: 0.0004 # 0-100: 0.0016 100-200: 0.0008 200-: 0.0004
  
  D_iter: 2
  G_iter: 1
  T_iter: 1
  lambdaGP: 10

  epochs: 400
  pretrained_epoch: 0

  save_img_path: ./valid_imgs/p2p/airplane_skeleton_surface
  
  recons_coef: 10
  cycle_coef: 10
  fp_coef: 10
  center_coef: 5
  cp_coef: 5

  save_pre_epoch: 10
  log_pre_iter: 25

test:
  split: test
  drop_last: False
  batch_size: 20
  autoencoder_epoch: 400
  save_img_path: ./test_imgs/p2p/airplane_scan_surface
  
  plot_npy_path: ../plot/npy/p2p
  plot_xml_path: ../plot/xml/p2p
  plot_jpg_path: ../plot/jpg/p2p

  points_index: [92]
